goal_setter/config/routes.rb
Rails.application.routes.draw do
  # get 'session/new'
  # get 'session/create'
  # get 'session/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:new, :create, :show] do 
    resources :goals,only:[:create,:new]
  end
  resource :session, only: [:new, :create, :destroy]
  resources :goals,except:[:new,:create]
end

goal_setter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goal_setter/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint(8)        not null, primary key
#  body       :string           not null
#  user_id    :integer          not null
#  public     :boolean          not null
#  completed  :boolean          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ApplicationRecord
  validates :body,:user_id,presence:true
  
  belongs_to :user,
  foreign_key: :user_id,
  class_name: :User
end

goal_setter/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email,:password_digest,:session_token, presence:true
  validates :password,length:{minimum:6,allow_nil:true}
  attr_reader :password
  
  before_validation :ensure_session_token
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end
  
  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user && user.is_password?(password) ? user : nil 
  end
    
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password) 
  end
  
  
  has_many :goals,
  foreign_key: :user_id,
  class_name: :Goal
end

goal_setter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  helper_method :current_user, :logged_in?
  
  def login(user)
    session[:session_token] = user.reset_session_token
  end
  
  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def logout
    current_user.reset_session_token
    session[:session_token] = nil 
  end
  
  def require_login
    
  end
  
end

goal_setter/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    @goals = Goal.all
  end
  
  def show
    @goal = Goal.find_by(id:params[:id])
  end
  
  def new
    @goal = Goal.new
    render :new
  end
  
  def create
    @goal = Goal.new(goal_params)
    
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
    
  end
  
  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end
  
  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @goal = Goal.find(params[:id])
     if @goal.destroy
       redirect_to goals_url
     else
       flash.now[:errors] = @goal.errors.full_messages
     end
  end
  
  def goal_params
    params.require(:goals).permit(:body,:public,:completed,:title)
  end
end

goal_setter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = 'Invalid Credentials'
      render :new
    end 
  end

  def destroy
    logout
    render :new
  end
end

goal_setter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end 
  end
  
  def show
    @user = User.find(params[:id])
    render :show 
  end
  
  
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

goal_setter/app/helpers/application_helper.rb
module ApplicationHelper
end

goal_setter/app/helpers/session_helper.rb
module SessionHelper
end

goal_setter/app/views/goals/new.html.erb
<h1>Create new Goal</h1>

<form  action="<%= user_goals_url  %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
  
  <label>
  Title:
  <input type="text" name="goal[title]" value="">
  </label>
  <br>
  <label>
  Body:
  <textarea name="goal[body]" rows="8" cols="80"></textarea>
  </label>
  <label>Private?
    <input type="checkbox" name="goal[public]" value="false">
  </label>
  <label>Completed?
    <input type="checkbox" name="goal[completed]" value="true">
  </label>
  
  <input type="submit" name="" value="New Goal">
  
  
</form>

goal_setter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>GoalSetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
    <form  action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      
      <input type="submit" name="" value=" SignOut">
    </form>
    <% else %>
      <input type="submit" name="" value="SignIn">
    <% end %>
    
    
    
    <%= yield %>
  </body>
</html>

goal_setter/app/views/users/new.html.erb
<h1>Create Account</h1>

<form action="<%= users_url %>" method="post">
  <input
  type="hidden"
  name="authenticity_token"
  value='<%= form_authenticity_token %>'
/>
  
  <label>
  Email:
    <input type="email" name="user[email]" value="">
  </label>
  <br>
  
  <label>
    Password:
    <input type="password" name="user[password]" value="">
  </label>
  <br>
  
  <input type="submit" value="Create User">
  
</form>

goal_setter/app/views/users/show.html.erb
<h1>current user page</h1>
<h2><%= @user.email %></h2>